if(!file.exists("./data")){dir.create("./data")}
url="https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(url,"data/zipfile.zip")
unzip(zipfile = "data/zipfile.zip", exdir = "./data")
household_Power<- read.table("data/household_power_consumption.txt", sep=";", header = T)
household_Power$Date<- as.Date(household_Power$Date, format = "%d/%m/%Y")
household_Power_sub<- with(household_Power, household_Power[(Date >= "2007-02-01" & Date <= "2007-02-02"), ])
summary(household_Power_sub)
##Plot4
household_Power_sub$Global_active_power<- as.numeric(as.character(household_Power_sub$Global_active_power))
household_Power_sub$Global_reactive_power<- as.numeric(as.character(household_Power_sub$Global_reactive_power))
household_Power_sub$Sub_metering_1<- as.numeric(as.character(household_Power_sub$Sub_metering_1))
household_Power_sub$Sub_metering_2<- as.numeric(as.character(household_Power_sub$Sub_metering_2))
household_Power_sub$Sub_metering_3<- as.numeric(as.character(household_Power_sub$Sub_metering_3))
household_Power_sub$Voltage<- as.numeric(as.character(household_Power_sub$Voltage))
datetime <- strptime(paste(household_Power_sub$Date, household_Power_sub$Time, sep=" "), "%Y-%m-%d %H:%M:%S")
png(file="plot4.png",width=480,height=480)
par(bg="white", mfrow = c(2, 2))
plot(datetime, household_Power_sub$Global_active_power, type = "l", xlab="", ylab = "Global Active Power")
plot(datetime, household_Power_sub$Voltage, type = "l", xlab="datetime", ylab = "Voltage")
plot(datetime, household_Power_sub$Sub_metering_1, type = "l", xlab="", ylab = "Energy sub metering")
lines(datetime, household_Power_sub$Sub_metering_2,type="l",col="red")
lines(datetime, household_Power_sub$Sub_metering_3,type="l",col="blue")
legend("topright", legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1,lwd=2,col = c("black", "red", "blue"))
plot(datetime, household_Power_sub$Global_reactive_power, type = "l", xlab="datetime", ylab = "Global_reactive_power (kilowatts)")
dev.off()
